[target.x86_64-unknown-linux-gnu]
image = "ubuntu:24.04"
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-dev libsoup2.4-dev libsoup-3.0-dev libatk1.0-dev libgdk-pixbuf2.0-dev libcairo2-dev libpango1.0-dev libudev-dev libusb-1.0-0-dev libglib2.0-dev libxdo-dev"
]