[application]
name = "Unruggable"
default_platform = "desktop"
asset_dir = "public"

[web.app]
title = ""

[bundle]
identifier = "com.unruggable"
publisher = "Unruggable Engineering Ltd."
copyright = "Copyright 2025 UnruggableEngineering"
category = "Utility"
icon = ["public/icon.png"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
